### ISSUE TITLE
KeyError: 'definitions'

### ISSUE THREAD

**Issue by elgalu** [garethr/openapi2jsonschema#1]
```
Downloading schema
Parsing schema
Generating shared definitions
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.12/bin/openapi2jsonschema", line 9, in <module>
    load_entry_point('openapi2jsonschema==0.6.0', 'console_scripts', 'openapi2jsonschema')()
  File "/home/user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/openapi2jsonschema/command.py", line 110, in default
    definitions = data['definitions']
KeyError: 'definitions'

```

**Comment by hrishin** [comment]
for me its giving
```
jsonref.JsonRefError
```

**Comment by AakashMasand** [comment]
I too get the KeyError: 'definitions' error. Any fixes for the same?

**Comment by Alebat** [comment]
Me too
